// English names and descriptions of the cards (effects are generated from data in both languages).
export const CARD_EN: Record<string, [name: string, blurb: string]> = {
  marshall: ['Marshall Plan', 'US economic aid program to rebuild Western Europe.'],
  berlin: ['Berlin Blockade', 'The USSR cuts land access to West Berlin; the West responds with an airlift.'],
  otan: ['NATO', 'The North Atlantic military alliance is founded.'],
  varsovia: ['Warsaw Pact', 'Military alliance of the USSR and its European allies.'],
  corea: ['Korean War', 'North Korea invades the South; UN and Chinese forces intervene.'],
  china49: ['Chinese Revolution', "The Communist Party takes power and proclaims the People's Republic."],
  cuba59: ['Cuban Revolution', 'A revolutionary movement overthrows the Batista government.'],
  misiles: ['Cuban Missile Crisis', 'Thirteen days of confrontation over Soviet missiles deployed in Cuba.'],
  suez: ['Suez Crisis', 'The UK, France and Israel intervene in Egypt after the canal is nationalized.'],
  hungria56: ['Hungary 1956', 'An uprising in Budapest is suppressed by Soviet troops.'],
  guatemala54: ['Guatemala 1954', 'A coup, backed from abroad, removes President Árbenz.'],
  iran53: ['Iran 1953', "A coup removes Prime Minister Mosaddegh and strengthens the Shah."],
  bandung: ['Bandung Conference', 'Asian and African countries meet and promote non-alignment.'],
  sputnik: ['Sputnik', 'The USSR launches the first artificial satellite.'],
  descolonizacion: ['Decolonization', 'Dozens of territories in Africa and Asia gain independence.'],
  truman: ['Truman Doctrine', 'The US pledges to support governments facing external pressure.'],
  japon: ['Occupation of Japan', 'Japan is rebuilt under Allied administration and signs a security treaty.'],
  dbp: ['Dien Bien Phu', 'French defeat in Indochina and the Geneva Accords.'],
  grecia46: ['Greek Civil War', 'Conflict between the Greek government and communist forces.'],
  bombasu: ['Soviet Atomic Bomb', 'The USSR conducts its first nuclear test.'],
  vietnam: ['Vietnam War', 'US intervention in the conflict between North and South Vietnam.'],
  praga: ['Prague Spring', 'Reforms in Czechoslovakia followed by a Warsaw Pact intervention.'],
  seisdias: ['Six-Day War', 'Israel fights Egypt, Syria and Jordan.'],
  yomkipur: ['Yom Kippur and Embargo', 'Arab–Israeli war followed by an oil embargo.'],
  chile73: ['Chile 1973', "A military coup ends Allende's government."],
  salt: ['SALT I', 'First strategic arms limitation agreement between the US and the USSR.'],
  nixon: ['Nixon in China', "First visit by a US president to the People's Republic."],
  angola75: ['Angola', 'Independence and civil war between movements with foreign backing.'],
  saigon: ['Fall of Saigon', 'Northern forces take the South Vietnamese capital.'],
  bangladesh: ['Bangladesh War', 'Indo-Pakistani war over the independence of East Pakistan.'],
  watergate: ['Watergate', 'The political scandal leads to the US president’s resignation.'],
  apolo: ['Apollo 11', 'First crewed mission to land on the Moon.'],
  petroleo: ['Oil Crisis', 'Rising crude prices hit industrialized economies.'],
  sandinista: ['Sandinista Revolution', 'The Sandinista Front overthrows the Somoza government.'],
  iran79: ['Iranian Revolution', 'The monarchy falls and the Islamic Republic is established.'],
  campdavid: ['Camp David Accords', 'Egypt and Israel negotiate a peace framework with US mediation.'],
  condor: ['Operation Condor', 'Coordination among the security services of several Southern Cone governments.'],
  dom65: ['Dominican Intervention', 'The US deploys troops during the Dominican civil war.'],
  ogaden: ['Ogaden War', 'Ethiopia and Somalia fight, with Soviet and Cuban support for Ethiopia.'],
  afg79: ['Afghanistan 1979', 'The USSR intervenes militarily in Afghanistan.'],
  ciclon: ['Operation Cyclone', 'Program supporting the Afghan resistance.'],
  iranirak: ['Iran–Iraq War', 'A long conflict between two major oil producers.'],
  malvinas: ['Falklands War', 'Argentina and the UK fight over the islands.'],
  solidaridad: ['Solidarity', 'The first independent trade union in the Soviet bloc emerges.'],
  ide: ['Strategic Defense Initiative', 'US missile-defense and advanced-technology program.'],
  ablearcher: ['Able Archer 83', 'A NATO exercise is read by Moscow as possible preparation for war.'],
  chernobil: ['Chernobyl', 'The nuclear accident has political and economic consequences in the USSR.'],
  perestroika: ['Perestroika', 'Economic reforms and political opening in the USSR.'],
  panama89: ['Panama 1989', 'The US intervenes militarily in Panama.'],
  contras: ['Contras', 'Internal conflict in Nicaragua with foreign support for the different sides.'],
  muro: ['Fall of the Berlin Wall', 'The borders between the two Germanys open.'],
  rev89: ['Revolutions of 1989', 'Political change in Poland, Hungary, Czechoslovakia and Romania.'],
  apartheid: ['End of Apartheid', 'South Africa dismantles its system of legal segregation.'],
  tiananmen: ['Tiananmen', 'Protests in Beijing end with a military crackdown.'],
  reagan: ['Reagan Doctrine', 'Support for movements and governments opposed to Soviet influence.'],
  libano82: ['Lebanon 1982', 'Israeli invasion and multinational forces in Lebanon.'],
  golfo91: ['Gulf War', 'A US-led coalition expels Iraq from Kuwait.'],
  yugoslavia: ['Yugoslav Wars', 'The breakup of Yugoslavia leads to several armed conflicts.'],
  kosovo: ['Kosovo', 'NATO air campaign during the Kosovo conflict.'],
  congo: ['Congo Wars', 'Regional conflicts following the Rwandan genocide.'],
  otan99: ['NATO Enlargement', 'Central and Eastern European countries join the alliance.'],
  once_s: ['9/11 and the War on Terror', 'After the attacks in the US, operations begin in Central Asia.'],
  irak03: ['Iraq 2003', 'A coalition invades Iraq and overthrows its government.'],
  bolivariana: ['Bolivarian Revolution', 'Venezuela launches a political project with alliances across Latin America.'],
  chinaascenso: ['Rise of China', 'Economic growth and a larger international presence for China.'],
  colores: ['Color Revolutions', 'Changes of government after protests in Georgia, Ukraine and elsewhere.'],
  georgia08: ['Georgia 2008', 'Armed conflict between Georgia and Russia over South Ossetia and Abkhazia.'],
  internet: ['Global Internet', 'The worldwide web goes mainstream and reshapes economy and politics.'],
  crisis08: ['2008 Financial Crisis', 'The banking crisis hits the advanced economies.'],
  washington: ['Washington Consensus', 'A set of economic reforms promoted in Latin America.'],
  marearosa: ['Pink Tide', 'Left-wing governments come to power in several Latin American countries.'],
  nk06: ['North Korean Nuclear Test', 'North Korea conducts its first test of a nuclear device.'],
  munich07: ['Munich Speech', 'Russia publicly criticizes the post-Cold War security order.'],
  primavera: ['Arab Spring', 'A wave of protests and political change across North Africa and the Middle East.'],
  libia11: ['Libya 2011', 'An international intervention accompanies the fall of the Libyan government.'],
  siria: ['Syrian Civil War', 'A conflict with many local and foreign actors.'],
  crimea: ['Crimea 2014', 'Russia incorporates Crimea; most states do not recognize the annexation.'],
  ucrania22: ['Ukraine 2022', 'Russia launches a full-scale invasion of Ukraine.'],
  finlandia: ['Finland and Sweden join NATO', 'Two Nordic countries end their military non-alignment and join the alliance.'],
  franja: ['Belt and Road', 'Chinese infrastructure and financing initiative in dozens of countries.'],
  gaza23: ['Gaza 2023', 'An armed escalation in Gaza has regional and diplomatic repercussions.'],
  taiwan: ['Taiwan Strait', 'Military exercises and political visits around Taiwan increase.'],
  chips: ['Chip War', 'Tariffs and trade restrictions on semiconductors.'],
  sahelgolpes: ['Sahel Coups', 'Changes of government by military means in several Sahel countries.'],
  vacunas: ['Vaccine Diplomacy', 'States donate and sell COVID-19 vaccines to other countries.'],
  sudan23: ['Sudan 2023', "Armed conflict breaks out between Sudan's military and paramilitary forces."],
  abraham: ['Abraham Accords', 'Normalization of relations between Israel and several Arab states.'],
  doce_dias: ['Twelve-Day War', 'A twelve-day military exchange between Israel and Iran, with strikes on nuclear sites.'],
  brics: ['Expanded BRICS', 'The group admits new members and partners.'],
  indpak25: ['India–Pakistan 2025', 'A military clash of a few days between two nuclear powers.'],
  venezuela: ['Venezuelan Crisis', 'Political tension, sanctions and migration in Venezuela.'],
  aukus: ['AUKUS and the Quad', 'Security cooperation among the US, Japan, India, Australia and the UK.'],
  turing: ['Turing Test', 'Alan Turing proposes a test of whether a machine can imitate a human.'],
  dartmouth: ['Dartmouth Conference', 'The term “artificial intelligence” is coined as a research field.'],
  inviernos: ['AI Winters', 'Funding cuts after unmet expectations in AI research.'],
  deepblue: ['Deep Blue beats Kasparov', 'An IBM computer wins a chess game against the world champion.'],
  alexnet: ['AlexNet and ImageNet', 'A deep neural network revolutionizes image recognition.'],
  alphago: ['AlphaGo', 'A DeepMind program beats Go champion Lee Sedol in Seoul.'],
  vigilancia: ['Algorithmic Surveillance', 'Large-scale facial recognition and data analysis systems spread.'],
  chatgpt: ['ChatGPT', 'A mass-market conversational assistant based on language models is launched.'],
  chipsexp: ['Chip Export Controls', 'The US restricts sales of advanced semiconductors to China.'],
  drones: ['Autonomous Drones in Ukraine', 'Drones with autonomous functions become widespread on the battlefield.'],
  bletchley: ['Bletchley AI Safety Summit', 'Twenty-eight countries sign a declaration on frontier AI risks.'],
  euia: ['EU AI Act', 'The European Union adopts a risk-tiered regulation for AI.'],
  deepfakes: ['Election Deepfakes', 'Synthetic content is used to influence election campaigns.'],
  deepseek: ['DeepSeek', 'A Chinese lab releases high-performing models at a lower reported cost.'],
  stargate: ['Project Stargate', 'A major US investment in AI infrastructure is announced.'],
  datacenters: ['Data Centers and Energy', "AI's power demand drives energy deals and new data centers."],
  institutos: ['AI Safety Institutes Network', 'Several countries create a network of institutes that evaluate advanced models.'],
  talento: ['AI Talent and Brain Drain', 'Researchers and engineers move to the technology hubs.'],
  ayuda: ['Military Aid', 'Weapons and equipment supplied to allied governments.'],
  propaganda: ['Propaganda', 'Information campaigns aimed at foreign public opinion.'],
  espionaje: ['Spy Network', 'Intelligence operations that weaken rival services.'],
  cumbre: ['Diplomatic Summit', 'A high-level meeting that eases tensions.'],
  asesores: ['Military Advisers', 'Technical personnel sent to countries where you already have a presence.'],
  score_eu: ['Scoring: Europe', 'Assesses the situation in Europe (Presence, Domination or Control).'],
  score_as: ['Scoring: Asia', 'Assesses the situation in Asia (Presence, Domination or Control).'],
  score_me: ['Scoring: Middle East', 'Assesses the situation in the Middle East (Presence, Domination or Control).'],
  score_af: ['Scoring: Africa', 'Assesses the situation in Africa (Presence, Domination or Control).'],
  score_am: ['Scoring: Americas', 'Assesses the situation in the Americas (Presence, Domination or Control).'],
};
